[program:snapmusic-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /data/snapmusic/artisan queue:work --sleep=3 --tries=3 --max-time=3600 --timeout=1805 --memory=512
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=rohan
numprocs=1
redirect_stderr=true
stdout_logfile=/data/snapmusic/storage/logs/snapmusic-worker.log
stopwaitsecs=1810
